version: '3'
services:
    vue-app:
        build: .
        ports:
            - "8081:8080"
        volumes:
            - .:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true  #this is only for windiws 

            